### PR TITLE
Changes regarding output addressing 

### PR DESCRIPTION
**Pull request by MicroBahner**
Hi Alex,
here are my changes as we discussed already. It's surely not finished, but we can discuss the changes.
I also changed the debug printing to a macro based version. I think this fits more seemlessly into the code and disrupts the code not as much as the big printing blocks with conditional compiling do. If DEBUG_PRINT is not defined its the same: the macro is empty, and no code is generated.

Franz-Peter

P.S. Unfortunately I did not do the DEBUG_PRINT changes in an own commit. Now the functional changes get lost in all that printing changes. These are the functional changes in the last commit:

line 588:    adding CV29 to the addresses that reset the cached own address:
 `case CV_29_CONFIG:`

line 1059: I think 'OutputAddress' schould be 'BoardAddress' here:
 `if((BoardAddress != getMyAddr()) && ( BoardAddress < 511 )) `

line 1117: not masking the state in extende accessory packets:
 `uint8_t state = pDccMsg->Data[2] ;// & 0b00011111;`

### CODE REVIEW

**Comment by kiwi64ajs** [comment]
This all looks good. I'm not 100% sure about the Output Address needing a +1 or not. Need to review the docs as it's pretty mind-bending

**Comment by kiwi64ajs** [comment]
Hi Peter,

> On 12/04/2018, at 8:27 AM, Franz-Peter <notifications@github.com> wrote:
> Hi Alex,
> here are my changes as we discussed already. It's surely not finished, but we can discuss the changes.
> I also changed the debug printing to a macro based version. I think this fits more seemlessly into the code and disrupt the code not as much as the big printing blocks with conditional compiling do. If DEBUG_PRINT is not defined its the same: the macro is empty, and no code is generated.
> 
That looks really good and makes things more readable - the only comment I would make is you’ve not used the "F()” syntax that stores the string in FLASH and doesn’t get loaded into RAM.

Anyway I’ve merged your PR so we’re on the same page and we can work through getting the finer details right

Alex

**Comment by MicroBahner** [comment]
Hi Alex,
> the only comment I would make is you’ve not used the "F()” syntax that stores the string in FLASH and doesn’t get loaded into RAM. 

The "F()" Syntax to not load the string into RAM is in the macro definition itself. Therefore you don't have to use it when calling the macro DB_PRINT.

Franz-Peter

**Comment by MicroBahner** [comment]
Hi Alex,
> I'm not 100% sure about the Output Address needing a +1 or not. 

I think we definitely need a +1 with the Output Addres. But we need only one addition and it's already there:
Line 1083:
`OutputAddress = (((BoardAddress - 1) << 2 ) | TurnoutPairIndex) + 1 ;`

I reviewd the MOROP papers and the papers of the RailCommunity ( they all are based on the NMRA papers). One thing is really the same in all of them: If CV1=1 and CV9=0 ( which is the default ) then board addressing and output addressing should correspond to the same DCC packet. And that is what the lib does now.

**Comment by kiwi64ajs** [comment]
> Hi Alex,
> 
> I'm not 100% sure about the Output Address needing a +1 or not.
> 
> I think we definitely need a +1 with the Output Addres. But we need only one addition and it's already there:
> Line 1083:
> OutputAddress = (((BoardAddress - 1) << 2 ) | TurnoutPairIndex) + 1 ;
> 
> I reviewd the MOROP papers and the papers of the RailCommunity ( they all are based on the NMRA papers). One thing is really the same in all of them: If CV1=1 and CV9=0 ( which is the default ) then board addressing and output addressing should correspond to the same DCC packet. And that is what the lib does now.
> 
Yeah I think this is the same conclusion I came to with all the spec ambiguity, however if I’ve done it twice then that’s bad...

Alex

Sent from my iPad

**Pull request merged**
