### PR TITLE
Unify the formatting

### PR DESCRIPTION
**Pull request by davidzuhn**
This PR is solely reformatting the two primary source files using Allman style braces, a wide line length, and #ifdef indentation that more or less matches the original code.   

This formatting was completed using the 'astyle' tool (instead of indent).   This tool correctly parses C++ binary constants (like 0b00001110) and can do a few more semantic checks than indent.   In particular, I added the option to surround all single-line conditional blocks with braces.   

The style file for 'astyle' is included, making it easy for someone else to reformat the code using the same arguments.   

I believe that there are no substantive changes to the code and there should be no functional difference.

### CODE REVIEW

**Comment by davidzuhn** [comment]
Retry DeepCode

**Comment by davidzuhn** [comment]
Retry DeepCode

**Comment by kiwi64ajs** [comment]
Hi David,
Just going back over this PR I see there are now a lot of merge conflicts in the NmraDcc.h & NmraDcc.cpp files.

I tried to remove those from the PR and just merge the other files so we can run the: astyle tool using the config you've come up with, but I think I've messed up the PR and I'm scared that if I merge it now it's going to delete the NmraDcc.h & NmraDcc.cpp files from my project and that would be bad.

Are you able to undo what I did and maybe just resubmit the PR excluding the changes to the NmraDcc.h & NmraDcc.cpp files but retaining all the other files so I can use it regularly to keep things tidy?

Regards
Alex Shepherd

**Comment by kiwi64ajs** [comment]
After making a mess of handling the PR due to my lack of git skills, I resorted to copying over the astyle config files and notes and committed them into the repo and then applied the style changes to the current master and committed those.
Thanks for contributing this as it should help with keeping the code style consistent

**Pull request closed without merging**
