### PR TITLE
ESP8266 Support

### PR DESCRIPTION
**Pull request by littleyoda**
attached a pull request to add support for the esp8266 microprocessors. 

I have only changed the way to access the eeprom. 

I encapsulate the commands to access the eeprom. Depending on the platform the right method to access  the eeprom is chosen now.

### CODE REVIEW

**Comment by kiwi64ajs** [comment]
Hmmm... I ran into similar issues on the Teensy 3.x so I wonder if we should make this change globally anyway and not just limit it to the ESP8266 variant...

Alex

**Comment by littleyoda** [comment]
This would be helpful.

It would also be nice if a "generic" way for store these values exists.

e.g. the esp8266 supports a filesystem on the flash-memory (https://github.com/esp8266/Arduino/blob/master/doc/filesystem.md)
or maybe someone wants to store the values on a sd card
or even he wants to store the values just in memory and not on a permanent storage

**Comment by MicroBahner** [comment]
Hi,
I think too it would be fine to generally change to the arduino EEPROM functions. This should work on all arduino compatible platforms without the need to use platformdependent code.

> _It would also be nice if a "generic" way for store these values exists._

Isn't that possible already? If you provide the 'notifyCVWrite()' and 'notifyCVRead()' functions than all reading and writing is done by these functions, and not by the internal eeprom_read_byte and eeprom_write_byte.

Regards
Franz-Peter

**Comment by kiwi64ajs** [comment]
Hi Guys,

> On 19/08/2016, at 8:19 PM, Franz-Peter notifications@github.com wrote:
> 
> Hi,
> I think too it would be fine to generally change to the arduino EEPROM functions. This should work on all arduino compatible platforms without the need to use platformdependent code.
> 
> Looking at this in more detail it appears that the ESP8266 EEPROM class actually emulates EEPROM with FLASH memory and it’s methods or API is different to the AVR's EEPROM class implementation in that it has an extra “commit()” and needs to call the begin(size) method at the start. 

Also the AVR implementation does not have any “currently busy writing” status which can cause the write() to delay for several ms... 

So these EEPROM classes are not yet equivalent so I’m inclined to add the patch but leave the AVR and Teensy implementation as they are for now…

> It would also be nice if a "generic" way for store these values exists.
> 
> Isn't that possible already? If you provide the 'notifyCVWrite()' and 'notifyCVRead()' functions than all reading and writing is done by these functions, and not by the internal eeprom_read_byte and eeprom_write_byte.
> 
> Yes, this should be the case. I did this to allow an alternative storage implementation to be added.

Regards

Alex Shepherd

p: +64-7-829 4441
m: +64-21-777764
e: kiwi64ajs@gmail.com

**Comment by littleyoda** [comment]
HI

Alex, you are right. Instead of EEPROM, the FLASH-Storage is used.

Thanks for pointing to notifyCVWrite/Read. I haven't realized that I can use this way for alternative storage access.

**Comment by kiwi64ajs** [comment]
I've manually merged this locally and bumped the versions

**Comment by littleyoda** [comment]
thanks, great.

**Pull request closed without merging**
